name: Pipeline

on:
  schedule:
    - cron: '0 1 * * MON,WED,FRI' # Agendamento para 01:00 nas segundas, quartas e sextas
  push: 
    branches-ignore: # Executa exceto nas branchs develop e master
      - 'develop'
      - 'master'
  pull_request:
    branches: 
      - 'develop'
      - 'main'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        #with:
        #  node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Create dev config file
        run: |
          mkdir -p cypress/configs
          echo '{
            "baseUrl": "${{ secrets.UI_BASE_URL }}",
            "apiUrl": "${{ secrets.API_BASE_URL }}",            
            "user": {
              "email": "${{ secrets.PROD_USER_EMAIL }}",
              "password": "${{ secrets.PROD_USER_PASSWORD }}"
            }
          }' > ./cypress/configs/dev.json

        # Execução de todos os testes (PR para main ou agendamento)
      - name: Run full test (PR main ou schedule)
        if: github.event_name == 'schedule' || github.event.pull_request.base.ref == 'main'
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.js
          command: npm run test:all
          continue-on-error: false # Falha o job se os testes falharem
      
      # Execução de smoke e regression teste (PR para develop)
      - name: Run Smoke and Regression tests (PR develop)
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop'
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.js
          env: "env=dev,grepTags='@smoke @regression',grepOmitFiltered=true"
        continue-on-error: false # Falha o job se os testes falharem

      # Execução de smoke e regression teste (push)
      - name: Run Smoke tests (push)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.js
          env: "env=dev,grepTags=@smoke,grepOmitFiltered=true"
        continue-on-error: false # Falha o job se os testes falharem