# This is a basic workflow to help you get started with Actions

name: Pipeline

# Controls when the workflow will run
on:
  push:
    branches: [ "develop", "main", "feature/pipeline" ]
  pull_request:
    branches: [ "develop", "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  e2e-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        #with:
        #  node-version: 18.x

      - name: Install Dependencies
        run: npm install

      - name: Create dev config file
        run: |
          mkdir -p cypress/configs
          echo '{
            "baseUrl": "${{ secrets.UI_BASE_URL }}",
            "apiUrl": "${{ secrets.API_BASE_URL }}",            
            "user": {
              "email": "${{ secrets.PROD_USER_EMAIL }}",
              "password": "${{ secrets.PROD_USER_PASSWORD }}"
            }
          }' > ./cypress/configs/dev.json
      
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          #env: env=ci
          config-file: cypress.config.js
          env: "env=dev"
        continue-on-error: false # Falha o job se os testes falharem

