# This is a basic workflow to help you get started with Actions

name: Pipeline

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 1 * * MON,WED,FRI' # Agendamento para 01:00 nas segundas, quartas e sextas
  push: 
    branches: [7-implementar-cypress-grep]
  pull_request:
    branches: [ "develop", "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  e2e-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        #with:
        #  node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Create dev config file
        run: |
          mkdir -p cypress/configs
          echo '{
            "baseUrl": "${{ secrets.UI_BASE_URL }}",
            "apiUrl": "${{ secrets.API_BASE_URL }}",            
            "user": {
              "email": "${{ secrets.PROD_USER_EMAIL }}",
              "password": "${{ secrets.PROD_USER_PASSWORD }}"
            }
          }' > ./cypress/configs/dev.json
      
      # Execução de smoke e regression teste quando tem PR em develop
      - name: Run Smoke and Regression tests (develop)
        if: github.ref == 'refs/heads/develop'
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          #env: env=ci
          config-file: cypress.config.js
          env: "env=dev,grepTags='@smoke @regression'"
        continue-on-error: false # Falha o job se os testes falharem

        # Execução de todos os testes em PR para main ou agendamento
      - name: Run full test (main ou schedule)
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          config-file: cypress.config.js
          env: env=dev
          command: npm run test:all
          continue-on-error: false # Falha o job se os testes falharem